// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcr1fZVqrIwC544BYnYm7j8tZv27Nl_Kg',
    appId: '1:908268878636:web:53aedb692fd742823c4a89',
    messagingSenderId: '908268878636',
    projectId: 'markx-35fec',
    authDomain: 'markx-35fec.firebaseapp.com',
    storageBucket: 'markx-35fec.firebasestorage.app',
    measurementId: 'G-610QFPXEQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJrDpoyfrHGN2FFdwXyGJNeAtD9pzxL4',
    appId: '1:908268878636:android:3d91fd8d112ea4693c4a89',
    messagingSenderId: '908268878636',
    projectId: 'markx-35fec',
    storageBucket: 'markx-35fec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgoETwso8QbHULDHWBMckvpopZHcQnBQ',
    appId: '1:908268878636:ios:1bfb094259ccf88e3c4a89',
    messagingSenderId: '908268878636',
    projectId: 'markx-35fec',
    storageBucket: 'markx-35fec.firebasestorage.app',
    iosBundleId: 'com.example.markx',
  );
}
